name: Publish to Gradle Plugin Portal
on:
  release:
    types:
      - created
  workflow_dispatch:
jobs:
  Publish to Plugin Portal:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
      - name: Publish
        env:
          GRADLE_PUBLISH_KEY: ${{secrets.GRADLE_PORTAL_KEY}}
          GRADLE_PUBLISH_SECRET: ${{secrets.GRADLE_PORTAL_SECRET}}
          ORG_GRADLE_PROJECT_signingKey: ${{secrets.MAVEN_CENTRAL_GPG_KEY}}
          ORG_GRADLE_PROJECT_signingPassword: ${{secrets.MAVEN_CENTRAL_GPG_PASSWORD}}
        run: ./gradlew publishPlugins --no-configuration-cache
  Upload SBOM:
    needs: Submit Dependencies
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Generate SBOM
        run: |
          curl -Lo $RUNNER_TEMP/sbom-tool https://github.com/microsoft/sbom-tool/releases/latest/download/sbom-tool-linux-x64
          chmod +x $RUNNER_TEMP/sbom-tool
          $RUNNER_TEMP/sbom-tool generate -b . -bc . -pn xml-processor-plugin -pv ${{github.ref_name}} -ps tacascer -nsb io.github.tacascer -V Verbose
      - uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: _manifest/spdx_2.2
      - name: SBOM upload
        uses: advanced-security/spdx-dependency-submission-action@v0.0.1
        with:
          filePath: "_manifest/spdx_2.2/"
